# Generated by Django 4.2.4 on 2023-08-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=500)),
                ('idpassport', models.CharField(max_length=500)),
                ('Yashashmanzili', models.CharField(max_length=500)),
                ('mfynomi', models.CharField(max_length=500)),
                ('kochanomi', models.CharField(max_length=500)),
                ('telefonraqami', models.CharField(max_length=500)),
                ('rasmvavidio', models.FileField(upload_to='')),
                ('matn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hokimiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orinbosar', models.CharField(max_length=500)),
                ('tashkilot', models.CharField(max_length=500)),
                ('muddat', models.DateField(auto_now_add=True)),
                ('bajarildi', models.BooleanField(default=False)),
                ('murajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sorov')),
            ],
        ),
    ]
