# Generated by Django 4.2.4 on 2023-08-25 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hokimiyat_muddat_holati_alter_hokimiyat_muddat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hokimiyat',
            name='muddat',
            field=models.IntegerField(default=datetime.datetime(2023, 8, 26, 14, 38, 18, 529270, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hokimiyat',
            name='tashkilot',
            field=models.CharField(blank=True, default='none', max_length=500),
        ),
    ]
