# Generated by Django 4.2.4 on 2023-08-26 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hokimiyat_muddat_alter_hokimiyat_tashkilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hokimiyat',
            name='muddat',
            field=models.IntegerField(default=datetime.datetime(2023, 8, 27, 12, 49, 8, 887709, tzinfo=datetime.timezone.utc)),
        ),
    ]
