# Generated by Django 4.2.4 on 2023-08-26 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hokimiyat_muddat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hokimiyat',
            name='muddat',
            field=models.IntegerField(default=datetime.datetime(2023, 8, 27, 13, 21, 13, 304876, tzinfo=datetime.timezone.utc)),
        ),
    ]
