# Generated by Django 4.2.5 on 2023-09-11 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hokimiyat_muddat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorov',
            name='ariza_mazmuni',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hokimiyat',
            name='muddat',
            field=models.IntegerField(default=datetime.datetime(2023, 9, 12, 5, 33, 51, 234713, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sorov',
            name='Yashashmanzili',
            field=models.CharField(choices=[('Guliston shaxar', 'Guliston shaxar'), ('Mirzaobod tumani', 'Mirzaobod tumani'), ('Yangiyer shaxar', 'Yangiyer shaxar'), ('Oqoltin tumani', 'Oqoltin tumani'), ('Sardoba tumani', 'Sardoba tumani'), ('Xovos tumani', 'Xovos tumani'), ('Sirdaryo tumani', 'Sirdaryo tumani'), ('Guliston tumani', 'Guliston tumani'), ('Sayhunobod tumani', 'Sayhunobod tumani'), ('Shirin Shahar', 'Shirin Shahar'), ('Boyovut tumani', 'Boyovut tumani')], default='Guliston shaxar', max_length=500, verbose_name='Iltoms Yashash Manzilingizni tanlang'),
        ),
        migrations.AlterField(
            model_name='sorov',
            name='fish',
            field=models.CharField(max_length=500, verbose_name='To`liq ismingizni kiriting?'),
        ),
        migrations.AlterField(
            model_name='sorov',
            name='idpassport',
            field=models.CharField(max_length=500, verbose_name='pasport seriasini kiriting'),
        ),
        migrations.AlterField(
            model_name='sorov',
            name='rasmvavidio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
